services:
  next:
    build:
      context: ./my-next-app
      dockerfile: ../docker/next.dev.Dockerfile
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - ./my-next-app:/app
    environment:
      WATCHPACK_POLLING: "true"
